Trendyol/quarkify

- tslint.json
> Add tslint file

- src/components/icon/icon.tsx
- src/components/icon/index.ts
- src/components/icon/test/icon.spec.jsx
- src/components/icon/test/icon.spec.tsx
- src/components/modal/modal.tsx
- src/components/modal/test/modal.spec.tsx
- src/interfaces/icon.tsx
- src/stories/icon.stories.tsx
- src/styles/_all.scss
- src/styles/_variables.scss
- src/styles/components/_icon.scss
- src/types/button.ts
- src/types/icon.ts
- src/types/input.ts
-Icon component created
-Some tests are added
-Modal component now uses Icon component to display its icon instead of custom i element.
-Default size variable changed
> Icon component

- src/components/icon/icon.tsx
- src/components/input/input.tsx
- src/components/select/index.ts
- src/components/select/select.tsx
- src/components/select/test/select.spec.tsx
- src/interfaces/select.tsx
- src/stories/select.stories.tsx
- src/styles/components/_select.scss
- src/types/select.ts
Select component has been added with its styles and tests.
> Select component

- src/components/input/input.tsx
- src/components/modal/modal-header.tsx
- src/stories/input.stories.tsx
- src/styles/components/_button.scss
- src/styles/components/_checkbox.scss
- src/styles/components/_radio.scss
- src/styles/components/_select.scss
And couple of input component fixes include:
-Input story now displays variant types
-Input now can have disabled prop to display disabled style class
> Accessibility of components improved

- src/components/popup/popup.tsx
> Revert "Change component to pureComponent"

- package-lock.json
- package.json
-Removed prettier because it conflicted with TSLint settings
-Added lint staged to husky to tslint --fix before each commit and push
> Lint staged configuration

- CHANGELOG.md
- package-lock.json
- package.json
- src/stories/demo.stories.tsx
- Add height 100% for demo stories img container
- Remove sass-loader package which is unnecessary
- Update changelog
> Safari fixes

- .circleci/config.yml
- package-lock.json
- package.json
Our new dist folder will be root to import components as "quarkify/components/button"
> Dist folder

- src/stories/radio.stories.tsx
- src/styles/components/_radio.scss
- src/styles/components/_switch.scss
-Add disabled class ant its styles to radio component
-Fix switch component error and disabled class names
> Disabled class added to radio component

- src/components/button/button.tsx
> Revert "Remove span element from button component"

- documents/_sidebar.md
- documents/components/accordion.md
- documents/components/box.md
- documents/components/icon.md
- documents/components/input.md
- documents/components/layout.md
- documents/components/list.md
- documents/components/loader.md
- documents/components/product-slider.md
- documents/components/switch.md
- documents/components/typography.md
- documents/index.html
Codesandbox demo parts are missing as of yet.
> Docsify update

- CHANGELOG.md
- package.json
- src/components/input/input.tsx
- src/styles/_all.scss
- src/styles/_reboot.scss
- src/styles/components/_accordion.scss
- src/styles/components/_link.scss
- src/styles/components/_scroll-to-top.scss
- `scroll-to-top` width and height
- reboot.css styles
- `scroll-to-top` animation
> Version 1.11.7

- CHANGELOG.md
- package.json
- src/components/button/button.tsx
- src/components/button/test/button.spec.tsx
- src/stories/select.stories.tsx
- `fluid` prop of the `button` component
> Version 1.12.1

- CHANGELOG.md
- package.json
- src/styles/components/_subheader.scss
- `subheader` height and title lineheight
> Version 1.15.2

- .storybook/config.js
- package-lock.json
- src/components/scroll-to-top/scroll-to-top.tsx
- src/stories/accordion.stories.tsx
- src/styles/_colors.scss
- src/styles/_font.scss
- src/styles/_globals.scss
- src/styles/_icon-url.scss
- src/styles/_variables.scss
- src/styles/components/_badge.scss
- src/styles/components/_bottom-sheet.scss
- src/styles/components/_box.scss
- src/styles/components/_button.scss
- src/styles/components/_checkbox.scss
- src/styles/components/_icon.scss
- src/styles/components/_input.scss
- src/styles/components/_layout.scss
- src/styles/components/_link.scss
- src/styles/components/_modal.scss
- src/styles/components/_popup.scss
- src/styles/components/_radio.scss
- src/styles/components/_rating.scss
- src/styles/components/_select.scss
- src/styles/components/_subheader.scss
- src/styles/components/_switch.scss
- src/styles/components/_typography.scss
Committer: antkaynak <antkaynak1@gmail.com>
> Refactor style structure

- .storybook/config.js
- CHANGELOG.md
- package-lock.json
- package.json
- src/components/scroll-to-top/scroll-to-top.tsx
- src/stories/accordion.stories.tsx
- src/styles/_font.scss
- src/styles/_globals.scss
- src/styles/_icon-url.scss
- src/styles/_variables.scss
- src/styles/components/_badge.scss
- src/styles/components/_bottom-sheet.scss
- src/styles/components/_box.scss
- src/styles/components/_button.scss
- src/styles/components/_checkbox.scss
- src/styles/components/_icon.scss
- src/styles/components/_input.scss
- src/styles/components/_layout.scss
- src/styles/components/_link.scss
- src/styles/components/_modal.scss
- src/styles/components/_popup.scss
- src/styles/components/_radio.scss
- src/styles/components/_rating.scss
- src/styles/components/_select.scss
- src/styles/components/_subheader.scss
- src/styles/components/_switch.scss
- src/styles/components/_typography.scss
> Version 1.15.3

- CHANGELOG.md
- package.json
- src/styles/components/_loader.scss
- src/styles/components/_popup.scss
z-index styles were wrong, fixed Loader and Popup components
> loader component z-index is changed from 1 to 1050

- CHANGELOG.md
- package.json
- src/components/not-found/not-found.tsx
- src/stories/not-found.stories.tsx
- src/styles/components/_not-found.scss
Fixes for `NotFound` component
> Fixes for NotFound component

- CHANGELOG.md
- package.json
- src/components/select/select.tsx
- Select component selected prop issue resolved.
> Select component selected prop issue resolved.

- package-lock.json
- package.json
- src/components/bottom-sheet/bottom-sheet.tsx
- src/components/bottom-sheet/test/bottom-sheet.spec.tsx
- src/styles/components/_bottom-sheet.scss
- src/styles/components/_modal.scss
This PR fixes the body's scrolling when bottom-sheet component opened.
Listens componentWillUpdate; if the case of opening or closing component, toggle the class of fixer of overflow.
> Fix: Add overflow hidden class to body when bottom-sheet opened

- package.json
- src/components/bottom-sheet/bottom-sheet.tsx
Reverted because causing width bug.
> Revert bug fix

- package-lock.json
- package.json
- src/components/checkbox/checkbox.tsx
- tsconfig.json
There was a conflict with checked property of checkbox, and it caused a bug when it is triggered from another source expect checkbox own.
> Fix problem with checkbox checked prop

- CHANGELOG.md
- package.json
- src/stories/step-progress-bar.stories.tsx
- src/styles/components/_step-progress-bar.scss
- Step Progress Bar z-index issue fixed
> Fix step progress bar z index issue

- CHANGELOG.md
- package.json
- src/components/subheader/subheader.tsx
- src/components/subheader/test/subheader.spec.tsx
- src/stories/subheader.stories.tsx
This changes should be published as 1.20.3
> resolve issue #229

- package-lock.json
- package.json
- src/components/bottom-sheet/bottom-sheet.tsx
- src/components/popup/popup.tsx
This change adds transition options for bottom sheet component. Also transition exit time decreases from 500ms to 200ms.
> Bottom sheet transition options

- package.json
- src/components/popup/popup.tsx
this line of code causes a scroll to top when we rerender a component (at that time window.pageYOffset might be 0)
> Add check before scroll

- CHANGELOG.md
- package.json
- src/components/bottom-sheet/bottom-sheet.tsx
problem: bu componenti product card içinde kullanıyoruz ve eğer kullanıcı bottom sheeti hiç açmadan product card'ı silersek bizi sayfanın en başına atıyor.
> add disable scroll for bottom sheet on unmount
